exclude: ".git"

repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
    - id: markdownlint
      stages: [pre-commit]
      args:
        - "*.md"

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.3.0
    hooks:
    - id: cspell
      stages: [pre-commit]
      args: ["-c", "./cspell/cspell.json", "--show-suggestions"]
